apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: d56k0gb7a-java-springboot
  janus-idp.io/tekton: d56k0gb7a-java-springboot
  backstage.io/kubernetes-id: d56k0gb7a-java-springboot
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: d56k0gb7a-java-springboot
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
